### ISSUE TITLE
Hunter missing Animal Companion Sheet and Spell Sheet

### ISSUE THREAD

**Issue by janiv** [marcusatbang/charactersheets#47]
I tried to find the script that configures these but was unsuccessful.

The hunter from ACG is missing the Animal Companion sheet and the spell sheet. As I work around, I downloaded a druid character sheet and printed out the pages I needed from there but would be nice to have it all in one package.

**Comment by marcusatbang** [comment]
Thanks. The script that configures them is part of the website, which is in a separate repo, so no wonder you couldn't find it:
https://github.com/marcusatbang/charactersheets-website/blob/play-2.3.8/public/data/pathfinder.json

**Comment by marcusatbang** [comment]
line 808 of that JSON file.
