### ISSUE TITLE
Pathfinder Unchained Consolidated Skills

### ISSUE THREAD

**Issue by efalder413** [marcusatbang/charactersheets#58]
An option for using the Pathfinder Unchained consolidated skills would be greatly appreciated. Full rules are on p54, but here's the short version:

![Screenshot of table 2-1 of Pathfinder Unchained](https://cloud.githubusercontent.com/assets/6841035/11678899/e76f326e-9e00-11e5-9138-4d4bb01a220f.png)

**Comment by efalder413** [comment]
and for class skills:
![class_skills1](https://cloud.githubusercontent.com/assets/6841035/11678964/7c26cf16-9e01-11e5-856b-7b0b4c135d0d.png)
![class_skills2](https://cloud.githubusercontent.com/assets/6841035/11678965/7c2b1616-9e01-11e5-9408-265e170c25e3.png)

**Comment by marcusatbang** [comment]
I've made a start on this, but it'll need some testing to make sure I've got it right.

**Comment by marcus-downing** [comment]
This is done, afaict.
