### ISSUE TITLE
skill list

### ISSUE THREAD

**Issue by arkantoster** [marcusatbang/charactersheets#60]
I've download a rogue sheet, and the ability key for search is wis, but the correct is int, and on hide it should be "+ size mod x 4", but it is "- size mod x 4"

**Comment by marcusatbang** [comment]
The INT will be fixed in the next version.

You're quite right, I keep getting + and - mixed up with size modifiers.

**Comment by marcus-downing** [comment]
INT is fixed.

I was right all along with the size modifier. In D&D 3.5, smaller characters get a **positive** size modifier.
http://dungeons.wikia.com/wiki/Table:_Creature_Size_and_Scale_(3.5e_Other)
