### ISSUE TITLE
Ultimate Intrigue Vigilante?

### ISSUE THREAD

**Issue by yamikuronue** [marcusatbang/charactersheets#61]
I don't see the Vigilante on here for Pathfinder? http://www.d20pfsrd.com/classes/base-classes/vigilante

**Comment by yamikuronue** [comment]
It seems to be in the code under the name Avenger, but I don't see it on the deployed site?

**Comment by marcusatbang** [comment]
It's still in progress. The _Avenger_ file there was a prototype based on the playtest.

**Comment by yamikuronue** [comment]
Ah, that's a shame. Is the file format documented someplace? I might be willing to help out :)

**Comment by marcusatbang** [comment]
The JSON file format isn't documented, though I did make a start on a verifier. It should be reasonably intelligible if you know JSON. The trick is to add both pages (near the top) and classes that use those pages (lower down). For example, the page variant `vigilante/avenger` corresponds to `slot="vigilante" variant="avenger"`.

btw, this repo has moved. You can find the latest copy here:
https://github.com/dyslexic-charactersheets/pages/tree/master/Pathfinder/Ultimate%20Intrigue
(I really should add redirects, change the link on the site etc)

**Comment by yamikuronue** [comment]
Ah, cool. I'm familiar with json. What's a .ai file?

**Comment by franciscocabral** [comment]
.ai is a adobe Ilustrator file

Em 25 de jul de 2016 08:37, "Yami" <notifications@github.com> escreveu:

**Comment by yamikuronue** [comment]
Ah. I don't have Illustrator. I can help with json-based stuff though if you point me in the right direction :)

**Comment by marcusatbang** [comment]
Try using InkScape, which is free. It's not as good as the thing that costs a bleeding fortune, of course, but it should at least open the files.

There are some [JavaScripts for automating illustrator](https://github.com/dyslexic-charactersheets/scripts) to do things like exporting all the Illustrator file as PDFs. They get committed to [the `assets` repo](https://github.com/dyslexic-charactersheets/assets), which the website references.

The [actual website code is in Scala](https://github.com/dyslexic-charactersheets/website/blob/master/app/controllers/Composer.scala), using the iTools Java library to do the heavy lifting of the PDFs.

Sorry it's all a bit messy. Partly that's a result of it simply being _large_, and partly by historical accident. If life were to ever shut up and leave me alone for long enough, I'd reimplement a lot of this to be tidier (and add nice features like saving characters to load later using local storage, or use the tool offline by compositing entirely in JavaScript... not an easy task). But it shows no sign of doing that. :smiley:

**Comment by marcusatbang** [comment]
Technically, [the Scala code](https://github.com/dyslexic-charactersheets/website/blob/master/app/models/gamedata.scala) serves as documentation of the JSON format. Practically that's over very little use since almost nobody knows Scala.

**Comment by marcus-downing** [comment]
It took a lot longer than I'd planned, but the Vigilante is done - as are the first batch of archetypes.
